name: "Build, Test, and Terraform Apply"

on:
  push:
    branches:
      - main

env:
  TF_CLOUD_ORGANIZATION: "Debugging"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_WORKSPACE: "Lambda-Terraform"
  CONFIG_DIRECTORY: "./"

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff
    - name: Run Ruff (linting and formatting)
      run: |
        ruff check .
        ruff format --check .
    - name: Setup TFLint
      uses: terraform-linters/setup-tflint@v3
      with:
        tflint_version: v0.44.1
    - name: Run TFLint
      run: tflint
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
    - name: Check Terraform formatting
      run: terraform fmt -check -recursive
    - name: Format Python code with Ruff
      run: ruff format .
    - name: Format Terraform code
      run: terraform fmt -recursive

  test:
    runs-on: ubuntu-latest
    needs: lint-and-format
    env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r lambda/requirements.txt
        pip install pytest
    - name: Run tests
      run: pytest -vv tests/test_lambda_function.py
  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r lambda/requirements.txt

      - name: Build Lambda layer
        run: |
          chmod +x ./build_layer.sh
          ./build_layer.sh
          echo "Contents of current directory:"
          ls -la
          echo "Contents of lambda directory:"
          ls -la lambda/

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
  

  terraform:
    needs: build-and-deploy
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init
      - name: Terraform Plan
        run: |
          terraform plan 
      - name: Verify lambda-layer.zip before Terraform apply
        run: |
          echo "Current directory: $(pwd)"
          ls -l lambda-layer.zip
          file lambda-layer.zip
          stat lambda-layer.zip
      - name: Terraform Apply
        run: |
          terraform apply -auto-approve
          